server:
  port: 11116
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
  instance:
    preferIpAddress: true
    appname: product
    virtual-host-name: product

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  eureka:
    enabled: true
    
password: '{cipher}AQBDb9xMYS1Orr1ZwXaADC65dWldpXACfOByPytu0V+Bmy9o0QCIe/6EZlNcfxYKY8glQdMEIXshUc+UxCCWxCXMVmusx52wEJ1aSQL1fuvKPbVPlIUzMWZ3ztq+cSxsIV9pGpFxnjIhfslFL4Z+Uc0Xrs++jwo7AV3KHnPtT5XhpfJIJFjkygbv9cYN5BsZBCAcpb64zb0NQW6rEW2VnH49b6zDbti2jMWpqflWJbIAjL5lO4j5sPLVOTSbuGXZpr4V/WeDS4yPetcuJaHzbZ/JOX66FPHjJCcgiOE7ilVmUf6UrL8K89Q5GZ+6YEyad/m2zJIGxGPM7K4n3GWQ+hqhkyaPog16/U5J+m1SWBl7NmMyQlGIiEPHh+Cg/OuKOzA='