server:
  port: 11117

ribbon:
  eureka:
    enabled: true
    
password: '{cipher}AQBDb9xMYS1Orr1ZwXaADC65dWldpXACfOByPytu0V+Bmy9o0QCIe/6EZlNcfxYKY8glQdMEIXshUc+UxCCWxCX
MVmusx52wEJ1aSQL1fuvKPbVPlIUzMWZ3ztq+cSxsIV9pGpFxnjIhfslFL4Z+Uc0Xrs++jwo7AV3KHnPtT5XhpfJIJFjkygbv9cYN5BsZBCA
cpb64zb0NQW6rEW2VnH49b6zDbti2jMWpqflWJbIAjL5lO4j5sPLVOTSbuGXZpr4V/WeDS4yPetcuJaHzbZ/JOX66FPHjJCcgiOE7ilVmUf6U
rL8K89Q5GZ+6YEyad/m2zJIGxGPM7K4n3GWQ+hqhkyaPog16/U5J+m1SWBl7NmMyQlGIiEPHh+Cg/OuKOzA='