server:
  port: 11113

#sidecar:
#  port: 11114

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  eureka:
    enabled: true

zuul:
  ignored-services: "*"
  routes:
    product:
      path: /product/**
      url: http://localhost:11116/product
    recommend:
      path: /recommend/**
      url: http://localhost:11115/recommend